export const fishData = [
  {
    "Image": "",
    "Name": "Salmon",
    "Price": "Base: 65 75\n 85\n 98\n 130",
    "Location": "Stream • Waterfall • Estuary • Ocean (Lookout, Forest) • Cavern (Air Mine)\nDuring Fall: River (Farm, Forest, Town)\nGift (Jim, Winter • Joko, Spring)",
    "Time": "All Day",
    "Weather": "Any",
    "SPR": "✓",
    "SUM": "",
    "FAL": "✓",
    "WIN": "✓",
    "Rarity": "Uncommon"
  },
  {
    "Image": "",
    "Name": "Giant snakehead",
    "Price": "Base: 80 92\n 104\n 120\n 160",
    "Location": "River (Farm, Town) • Lake\nUnobtainable",
    "Time": "Morning\nEvening",
    "Weather": "Sunny",
    "SPR": "",
    "SUM": "✓",
    "FAL": "✓",
    "WIN": "",
    "Rarity": "Uncommon"
  },
  {
    "Image": "",
    "Name": "Catfish",
    "Price": "Base: 30 35\n 39\n 45\n 60",
    "Location": "Rice Field • Pond • River (Farm, Forest) • Stream • River • Mangrove • Cavern (Entrance) • Lake\nTrash Cans (Spring • Summer)\nBeach Shack (Spring)",
    "Time": "Morning\nNight",
    "Weather": "Sunny\nWindy",
    "SPR": "✓",
    "SUM": "✓",
    "FAL": "",
    "WIN": "",
    "Rarity": "Common"
  },
  {
    "Image": "",
    "Name": "Flowerhorn",
    "Price": "Base: 65 75\n 85\n 98\n 130",
    "Location": "Cavern (Entrance, Air Mine, Water Mine) • Lake",
    "Time": "All Day",
    "Weather": "Any",
    "SPR": "✓",
    "SUM": "✓",
    "FAL": "✓",
    "WIN": "✓",
    "Rarity": "Uncommon"
  },
  {
    "Image": "",
    "Name": "Tilapia",
    "Price": "Base: 30 35\n 39\n 45\n 60",
    "Location": "Rice Field • River (Farm, Forest) • Stream • Cavern (Entrance, Earth Mine, Fire Mine) • Lake",
    "Time": "All Day",
    "Weather": "Any",
    "SPR": "✓",
    "SUM": "✓",
    "FAL": "✓",
    "WIN": "",
    "Rarity": "Common"
  },
  {
    "Image": "",
    "Name": "Red king arowana",
    "Price": "Base: 620 713\n 806\n 930\n 1240",
    "Location": "Cavern (Fire Mine, Air Mine)\nUnobtainable",
    "Time": "Afternoon\nEvening",
    "Weather": "Rain",
    "SPR": "",
    "SUM": "",
    "FAL": "✓\n(22-28)",
    "WIN": "",
    "Rarity": "Legendary"
  },
  {
    "Image": "",
    "Name": "Silver arowana",
    "Price": "Base: 65 75\n 85\n 98\n 130",
    "Location": "River (Town) • Cavern (Water Mine) • Lake\nTrash Cans (Winter)",
    "Time": "Morning\nAfternoon",
    "Weather": "Sunny\nRain\nWindy",
    "SPR": "",
    "SUM": "",
    "FAL": "",
    "WIN": "✓",
    "Rarity": "Uncommon"
  },
  {
    "Image": "",
    "Name": "Koi",
    "Price": "Base: 65 75\n 85\n 98\n 130",
    "Location": "River (Town) • Waterfall • Cavern (Entrance, Earth Mine) • Lake",
    "Time": "Morning",
    "Weather": "Any",
    "SPR": "",
    "SUM": "✓",
    "FAL": "",
    "WIN": "",
    "Rarity": "Uncommon"
  },
  {
    "Image": "",
    "Name": "Black phantom ghost fish",
    "Price": "Base: 25 29\n 33\n 38\n 50",
    "Location": "River (Farm, Town) • Stream • Cavern (Fire Mine)\nTrash Cans (Spring)",
    "Time": "Any",
    "Weather": "Sunny\nWindy",
    "SPR": "✓",
    "SUM": "",
    "FAL": "",
    "WIN": "",
    "Rarity": "Common"
  },
  {
    "Image": "",
    "Name": "Gator gar",
    "Price": "Base: 745 857\n 969\n 1118\n 1490",
    "Location": "River (Forest) • Lake\nImpossible to reel in with current equipment",
    "Time": "Afternoon",
    "Weather": "Rain\nStorm",
    "SPR": "✓ (15-28)",
    "SUM": "",
    "FAL": "",
    "WIN": "",
    "Rarity": "Legendary"
  },
  {
    "Image": "",
    "Name": "Rainbow fish",
    "Price": "Base: 50 58\n 65\n 75\n 100",
    "Location": "Rice Field • River (Farm, Town) • Mangrove • Lake",
    "Time": "All Day",
    "Weather": "Any",
    "SPR": "",
    "SUM": "",
    "FAL": "✓",
    "WIN": "",
    "Rarity": "Uncommon"
  },
  {
    "Image": "",
    "Name": "Tiger barb",
    "Price": "Base: 25 29\n 33\n 38\n 50",
    "Location": "River (Farm, Town) • Stream • Cavern (Earth Mine) • Lake",
    "Time": "All Day",
    "Weather": "Sunny\nWindy",
    "SPR": "",
    "SUM": "",
    "FAL": "✓",
    "WIN": "",
    "Rarity": "Common"
  },
  {
    "Image": "",
    "Name": "Crayfish",
    "Price": "Base: 25 29\n 33\n 38\n 50",
    "Location": "Rice Field • Pond • River (Farm, Forest, Town) • Stream • Waterfall • Cavern (Fire Mine)",
    "Time": "Evening\nNight",
    "Weather": "Any",
    "SPR": "✓",
    "SUM": "✓",
    "FAL": "✓",
    "WIN": "",
    "Rarity": "Common"
  },
  {
    "Image": "",
    "Name": "Freshwater eel",
    "Price": "Base: 30 35\n 39\n 45\n 60",
    "Location": "Rice Field • River (Farm, Forest) • Stream • Estuary • Cavern (Air Mine)\nUnobtainable",
    "Time": "Morning\nNight",
    "Weather": "Sunny\nRain\nStorm",
    "SPR": "",
    "SUM": "✓",
    "FAL": "",
    "WIN": "",
    "Rarity": "Common"
  },
  {
    "Image": "",
    "Name": "Goldfish",
    "Price": "Base: 55 63\n 72\n 83\n 110",
    "Location": "River (Farm, Forest, Town) • Estuary • Cavern (Air Mine) • Lake",
    "Time": "Morning\nAfternoon\nEvening",
    "Weather": "Any",
    "SPR": "",
    "SUM": "✓",
    "FAL": "✓",
    "WIN": "",
    "Rarity": "Uncommon"
  },
  {
    "Image": "",
    "Name": "Snakehead",
    "Price": "Base: 30 35\n 39\n 45\n 60",
    "Location": "Pond • River (Forest) • Stream • Cavern (Air Mine) • Lake\nUnobtainable",
    "Time": "Morning\nEvening",
    "Weather": "Sunny",
    "SPR": "✓",
    "SUM": "✓",
    "FAL": "",
    "WIN": "✓",
    "Rarity": "Common"
  },
  {
    "Image": "",
    "Name": "Bluegill",
    "Price": "Base: 30 35\n 39\n 45\n 60",
    "Location": "Pond • River (Town) • Stream • Waterfall • Cavern (Water Mine) • Lake",
    "Time": "Morning\nEvening",
    "Weather": "Any",
    "SPR": "",
    "SUM": "",
    "FAL": "✓",
    "WIN": "",
    "Rarity": "Common"
  },
  {
    "Image": "",
    "Name": "Arapaima",
    "Price": "Base: 355 408\n 462\n 533\n 710",
    "Location": "River (Forest) • Waterfall • Ocean (Forest)\nUnobtainable",
    "Time": "All Day",
    "Weather": "Any",
    "SPR": "✓",
    "SUM": "✓",
    "FAL": "✓",
    "WIN": "",
    "Rarity": "Super rare"
  },
  {
    "Image": "",
    "Name": "Zebra fish",
    "Price": "Base: 25 29\n 33\n 38\n 50",
    "Location": "Rice Field • Pond • River (Town) • Cavern (Fire Mine)\nUnobtainable",
    "Time": "Morning\nAfternoon",
    "Weather": "Any",
    "SPR": "✓",
    "SUM": "✓",
    "FAL": "✓",
    "WIN": "✓",
    "Rarity": "Common"
  },
  {
    "Image": "",
    "Name": "Golden gar",
    "Price": "Base: 105 121\n 137\n 158\n 210",
    "Location": "River (Farm) • Cavern (Earth Mine) • Lake\nUnobtainable",
    "Time": "All Day",
    "Weather": "Any",
    "SPR": "",
    "SUM": "✓",
    "FAL": "",
    "WIN": "",
    "Rarity": "Rare"
  },
  {
    "Image": "",
    "Name": "Chub",
    "Price": "Base: 25 29\n 33\n 38\n 50",
    "Location": "River (Forest, Town) • Stream • Waterfall • Cavern (Entrance, Fire Mine) • Lake",
    "Time": "Morning\nAfternoon\nEvening",
    "Weather": "Any",
    "SPR": "",
    "SUM": "",
    "FAL": "",
    "WIN": "✓",
    "Rarity": "Common"
  },
  {
    "Image": "",
    "Name": "Brown trout",
    "Price": "Base: 30 35\n 39\n 45\n 60",
    "Location": "River (Forest, Town) • Stream • Waterfall • Cavern (Earth Mine) • Lake\nTrash cans (Any)",
    "Time": "All Day",
    "Weather": "Sunny\nRain\nWindy\nStorm",
    "SPR": "✓",
    "SUM": "✓",
    "FAL": "✓",
    "WIN": "✓",
    "Rarity": "Common"
  },
  {
    "Image": "",
    "Name": "Cobia",
    "Price": "Base: 80 92\n 104\n 120\n 160",
    "Location": "Estuary • Ocean (Dock, Beach, Lookout) • Mangrove • Cavern (Water Mine)\nUnobtainable",
    "Time": "Afternoon",
    "Weather": "Sunny\nRain\nWindy",
    "SPR": "",
    "SUM": "✓",
    "FAL": "✓",
    "WIN": "",
    "Rarity": "Uncommon"
  },
  {
    "Image": "",
    "Name": "Frogfish",
    "Price": "Base: 90 104\n 117\n 135\n 180",
    "Location": "Ocean (Beach) • Cavern (Earth Mine)",
    "Time": "All Day",
    "Weather": "Rain",
    "SPR": "✓",
    "SUM": "✓",
    "FAL": "✓",
    "WIN": "✓",
    "Rarity": "Rare"
  },
  {
    "Image": "",
    "Name": "Monkfish",
    "Price": "Base: 125 144\n 163\n 188\n 250",
    "Location": "Ocean (Dock, Lookout, Forest)\nUnobtainable",
    "Time": "Evening\nNight",
    "Weather": "Sunny\nWindy",
    "SPR": "",
    "SUM": "",
    "FAL": "✓",
    "WIN": "",
    "Rarity": "Rare"
  },
  {
    "Image": "",
    "Name": "Yellowtail",
    "Price": "Base: 145 167\n 189\n 218\n 290",
    "Location": "Ocean (Dock, Forest) • Cavern (Water Mine)\nGift (Sunny, Spring)",
    "Time": "All Day",
    "Weather": "Rain\nWindy\nStorm",
    "SPR": "✓",
    "SUM": "✓",
    "FAL": "✓",
    "WIN": "",
    "Rarity": "Rare"
  },
  {
    "Image": "",
    "Name": "Tuna",
    "Price": "Base: 80 92\n 104\n 120\n 160",
    "Location": "Ocean (Dock, Forest)\nGift (Theo, Summer)",
    "Time": "Evening",
    "Weather": "Any",
    "SPR": "✓",
    "SUM": "",
    "FAL": "✓",
    "WIN": "",
    "Rarity": "Uncommon"
  },
  {
    "Image": "",
    "Name": "Pufferfish",
    "Price": "Base: 90 104\n 117\n 135\n 180",
    "Location": "Ocean (Beach, Lookout, Forest) • Cavern (Entrance)",
    "Time": "Evening",
    "Weather": "Sunny\nRain\nWindy\nStorm",
    "SPR": "",
    "SUM": "",
    "FAL": "",
    "WIN": "✓",
    "Rarity": "Rare"
  },
  {
    "Image": "",
    "Name": "Ruby red dragonet",
    "Price": "Base: 50 58\n 65\n 75\n 100",
    "Location": "Ocean (Beach, Lookout) • Cavern (Earth Mine)",
    "Time": "All Day",
    "Weather": "Any",
    "SPR": "✓",
    "SUM": "✓",
    "FAL": "✓",
    "WIN": "✓",
    "Rarity": "Uncommon"
  },
  {
    "Image": "",
    "Name": "Yellow moray eel",
    "Price": "Base: 745 857\n 969\n 1118\n 1490",
    "Location": "Ocean (Beach)\nUnobtainable",
    "Time": "Night",
    "Weather": "Rain\nWindy\nStorm",
    "SPR": "✓\n(8-14)",
    "SUM": "✓\n(8-14)",
    "FAL": "",
    "WIN": "",
    "Rarity": "Legendary"
  },
  {
    "Image": "",
    "Name": "Pink snapper",
    "Price": "Base: 230 265\n 299\n 345\n 460",
    "Location": "Ocean (Lookout) • Cavern (Fire Mine)\nUnobtainable",
    "Time": "Afternoon\nEvening",
    "Weather": "Any",
    "SPR": "✓",
    "SUM": "",
    "FAL": "",
    "WIN": "✓",
    "Rarity": "Super rare"
  },
  {
    "Image": "",
    "Name": "Squid",
    "Price": "Base: 30 35\n 39\n 45\n 60",
    "Location": "Estuary • Ocean (Dock, Beach, Lookout, Forest) • Cavern (Water Mine)\nUnobtainable",
    "Time": "Night",
    "Weather": "Any",
    "SPR": "✓",
    "SUM": "✓",
    "FAL": "✓",
    "WIN": "",
    "Rarity": "Common"
  },
  {
    "Image": "",
    "Name": "Octopus",
    "Price": "Base: 105 121\n 137\n 158\n 210",
    "Location": "Ocean (Dock, Beach)\nUnobtainable",
    "Time": "Evening\nNight",
    "Weather": "Sunny\nRain",
    "SPR": "",
    "SUM": "",
    "FAL": "✓",
    "WIN": "",
    "Rarity": "Rare"
  },
  {
    "Image": "",
    "Name": "Giant mudskipper",
    "Price": "Base: 30 35\n 39\n 45\n 60",
    "Location": "Rice Field • Pond • Ocean (Forest) • Mangrove • Cavern (Water Mine)",
    "Time": "All Day",
    "Weather": "Sunny\nWindy",
    "SPR": "",
    "SUM": "",
    "FAL": "",
    "WIN": "✓",
    "Rarity": "Common"
  },
  {
    "Image": "",
    "Name": "Grouper",
    "Price": "Base: 80 92\n 104\n 120\n 160",
    "Location": "Ocean (Dock, Beach) • Mangrove • Cavern (Entrance, Fire Mine)\nUnobtainable",
    "Time": "All Day",
    "Weather": "Any",
    "SPR": "✓",
    "SUM": "✓",
    "FAL": "✓",
    "WIN": "",
    "Rarity": "Uncommon"
  },
  {
    "Image": "",
    "Name": "Sea cucumber",
    "Price": "Base: 105 121\n 137\n 158\n 210",
    "Location": "Ocean (Forest) • Cavern (Water Mine)\nUnobtainable",
    "Time": "All Day",
    "Weather": "Sunny\nRain\nSnow\nBlizzard\nStorm",
    "SPR": "✓",
    "SUM": "✓",
    "FAL": "✓",
    "WIN": "✓",
    "Rarity": "Rare"
  },
  {
    "Image": "",
    "Name": "Parrotfish",
    "Price": "Base: 40 46\n 52\n 60\n 80",
    "Location": "Ocean (Beach) • Cavern (Air Mine)\nUnobtainable",
    "Time": "Morning\nAfternoon",
    "Weather": "Any",
    "SPR": "✓",
    "SUM": "✓",
    "FAL": "✓",
    "WIN": "✓",
    "Rarity": "Common"
  },
  {
    "Image": "",
    "Name": "Polka-dot batfish",
    "Price": "Base: 40 46\n 52\n 60\n 80",
    "Location": "Ocean (Dock, Forest)\nUnobtainable",
    "Time": "All Day",
    "Weather": "Rain\nSnow\nBlizzard\nWindy\nStorm",
    "SPR": "✓",
    "SUM": "✓",
    "FAL": "✓",
    "WIN": "✓",
    "Rarity": "Uncommon"
  },
  {
    "Image": "",
    "Name": "Flameback fish",
    "Price": "Base: 50 58\n 65\n 75\n 100",
    "Location": "Ocean (Dock, Beach) • Cavern (Earth Mine)",
    "Time": "Afternoon\nEvening\nNight",
    "Weather": "Sunny\nSnow\nBlizzard\nStorm",
    "SPR": "✓",
    "SUM": "✓",
    "FAL": "",
    "WIN": "✓",
    "Rarity": "Uncommon"
  },
  {
    "Image": "",
    "Name": "Giant stingray",
    "Price": "Base: 355 408\n 462\n 533\n 710",
    "Location": "Ocean (Dock, Lookout)\nImpossible to reel in with current equipment",
    "Time": "Afternoon",
    "Weather": "Sunny\nWindy",
    "SPR": "",
    "SUM": "",
    "FAL": "",
    "WIN": "✓",
    "Rarity": "Super rare"
  },
  {
    "Image": "",
    "Name": "Lobster",
    "Price": "Base: 105 121\n 137\n 158\n 210",
    "Location": "Estuary • Ocean (Dock, Lookout) • Cavern (Air Mine)\nGift (Scott, Spring)",
    "Time": "All Day",
    "Weather": "Sunny\nRain\nWindy\nStorm",
    "SPR": "✓",
    "SUM": "✓",
    "FAL": "✓",
    "WIN": "✓",
    "Rarity": "Rare"
  },
  {
    "Image": "",
    "Name": "Lionfish",
    "Price": "Base: 105 121\n 137\n 158\n 210",
    "Location": "Ocean (Beach, Lookout) • Cavern (Fire Mine)",
    "Time": "Evening",
    "Weather": "Sunny\nRain\nStorm",
    "SPR": "",
    "SUM": "✓",
    "FAL": "",
    "WIN": "",
    "Rarity": "Rare"
  },
  {
    "Image": "",
    "Name": "Damselfish",
    "Price": "Base: 210 242\n 273\n 315\n 420",
    "Location": "Ocean (Lookout) • Cavern (Fire Mine)",
    "Time": "Morning\nAfternoon\nEvening",
    "Weather": "Sunny\nRain\nSnow\nBlizzard\nWindy",
    "SPR": "✓",
    "SUM": "✓",
    "FAL": "✓",
    "WIN": "✓",
    "Rarity": "Super rare"
  },
  {
    "Image": "",
    "Name": "Mandarin",
    "Price": "Base: 210 242\n 273\n 315\n 420",
    "Location": "Ocean (Beach, Forest)",
    "Time": "Morning\nAfternoon",
    "Weather": "Sunny\nRain\nWindy\nStorm",
    "SPR": "✓",
    "SUM": "✓",
    "FAL": "✓",
    "WIN": "✓",
    "Rarity": "Super rare"
  },
  {
    "Image": "",
    "Name": "Archer",
    "Price": "Base: 90 104\n 117\n 135\n 180",
    "Location": "River (Forest, Town) • Estuary • Ocean (Lookout, Forest) • Mangrove • Cavern (Fire Mine)",
    "Time": "All Day",
    "Weather": "Any",
    "SPR": "",
    "SUM": "",
    "FAL": "",
    "WIN": "✓",
    "Rarity": "Rare"
  },
  {
    "Image": "",
    "Name": "Angelfish",
    "Price": "Base: 55 63\n 72\n 83\n 110",
    "Location": "River (Forest) • Stream • Waterfall • Cavern (Earth Mine, Air Mine)",
    "Time": "Morning\nAfternoon",
    "Weather": "Sunny\nRain\nStorm",
    "SPR": "✓",
    "SUM": "✓",
    "FAL": "",
    "WIN": "",
    "Rarity": "Uncommon"
  },
  {
    "Image": "",
    "Name": "Blue tang",
    "Price": "Base: 30 35\n 39\n 45\n 60",
    "Location": "Ocean (Dock, Beach, Lookout) • Cavern (Entrance, Earth Mine)",
    "Time": "All Day",
    "Weather": "Any",
    "SPR": "✓",
    "SUM": "",
    "FAL": "",
    "WIN": "✓",
    "Rarity": "Common"
  },
  {
    "Image": "",
    "Name": "Clownfish",
    "Price": "Base: 25 29\n 33\n 38\n 50",
    "Location": "Ocean (Dock, Beach) • Cavern (Air Mine)",
    "Time": "Morning\nAfternoon\nEvening",
    "Weather": "Sunny\nRain\nStorm",
    "SPR": "",
    "SUM": "✓",
    "FAL": "",
    "WIN": "",
    "Rarity": "Common"
  },
  {
    "Image": "",
    "Name": "Firefish",
    "Price": "Base: 50 58\n 65\n 75\n 100",
    "Location": "Ocean (Beach, Lookout) • Cavern (Fire Mine)",
    "Time": "Afternoon\nEvening\nNight",
    "Weather": "Rain\nWindy\nStorm",
    "SPR": "",
    "SUM": "✓",
    "FAL": "✓",
    "WIN": "",
    "Rarity": "Uncommon"
  },
  {
    "Image": "",
    "Name": "Asian sheepshead",
    "Price": "Base: 260 299\n 338\n 390\n 520",
    "Location": "Ocean (Dock, Beach, Lookout) • Cavern (Water Mine)\nUnobtainable",
    "Time": "All Day",
    "Weather": "Any",
    "SPR": "",
    "SUM": "",
    "FAL": "",
    "WIN": "✓",
    "Rarity": "Super rare"
  },
  {
    "Image": "",
    "Name": "Boxfish",
    "Price": "Base: 30 35\n 39\n 45\n 60",
    "Location": "Ocean (Dock, Lookout, Forest) • Cavern (Air Mine)",
    "Time": "All Day",
    "Weather": "Any",
    "SPR": "✓",
    "SUM": "",
    "FAL": "✓",
    "WIN": "✓",
    "Rarity": "Common"
  },
  {
    "Image": "",
    "Name": "Mackerel",
    "Price": "Base: 30 35\n 39\n 45\n 60",
    "Location": "Ocean (Dock, Beach, Lookout, Forest) • Cavern (Water Mine)",
    "Time": "All Day",
    "Weather": "Any",
    "SPR": "✓",
    "SUM": "✓",
    "FAL": "✓",
    "WIN": "✓",
    "Rarity": "Common"
  },
  {
    "Image": "",
    "Name": "Yellowfin tuna",
    "Price": "Base: 125 144\n 163\n 188\n 250",
    "Location": "Ocean (Dock, Beach, Forest)\nUnobtainable",
    "Time": "Evening",
    "Weather": "Sunny\nBlizzard\nStorm",
    "SPR": "",
    "SUM": "",
    "FAL": "",
    "WIN": "✓",
    "Rarity": "Rare"
  },
  {
    "Image": "",
    "Name": "Crab",
    "Price": "Base: 55 63\n 72\n 83\n 110",
    "Location": "Rice Field • Estuary • Ocean (Dock, Beach, Lookout, Forest) • Mangrove • Cavern (Fire Mine)\nTrash Cans (Fall)",
    "Time": "Morning\nNight",
    "Weather": "Any",
    "SPR": "✓",
    "SUM": "✓",
    "FAL": "✓",
    "WIN": "✓",
    "Rarity": "Uncommon"
  },
  {
    "Image": "",
    "Name": "Swordfish",
    "Price": "Base: 125 144\n 163\n 188\n 250",
    "Location": "Ocean (Dock, Beach, Forest) • Cavern (Earth Mine)\nUnobtainable",
    "Time": "Morning\nAfternoon",
    "Weather": "Rain\nSnow\nBlizzard\nStorm",
    "SPR": "✓",
    "SUM": "",
    "FAL": "",
    "WIN": "✓",
    "Rarity": "Rare"
  },
  {
    "Image": "",
    "Name": "Cod",
    "Price": "Base: 30 35\n 39\n 45\n 60",
    "Location": "Estuary • Ocean (Lookout, Forest)",
    "Time": "Evening\nNight",
    "Weather": "Sunny\nSnow\nWindy\nStorm",
    "SPR": "",
    "SUM": "",
    "FAL": "✓",
    "WIN": "✓",
    "Rarity": "Common"
  },
  {
    "Image": "",
    "Name": "Barracuda",
    "Price": "Base: 65 75\n 85\n 98\n 130",
    "Location": "Ocean (Dock, Beach, Forest) • Mangrove\nGift (Wataru, Summer)",
    "Time": "Morning\nAfternoon\nEvening",
    "Weather": "Sunny\nRain\nWindy\nStorm",
    "SPR": "",
    "SUM": "✓",
    "FAL": "",
    "WIN": "",
    "Rarity": "Uncommon"
  },
  {
    "Image": "",
    "Name": "Giant sea bass",
    "Price": "Base: 845 972\n 1099\n 1268\n 1690",
    "Location": "Ocean (Forest)",
    "Time": "Morning\nNight",
    "Weather": "Rain\nWindy\nStorm",
    "SPR": "",
    "SUM": "",
    "FAL": "✓\n1-7",
    "WIN": "",
    "Rarity": "Legendary"
  },
  {
    "Image": "",
    "Name": "Sardine",
    "Price": "Base: 25 29\n 33\n 38\n 50",
    "Location": "Estuary • Ocean (Dock) • Cavern (Air Mine)",
    "Time": "Night",
    "Weather": "Any",
    "SPR": "✓",
    "SUM": "✓",
    "FAL": "✓",
    "WIN": "✓",
    "Rarity": "Common"
  },
  {
    "Image": "",
    "Name": "Red snapper",
    "Price": "Base: 105 121\n 137\n 158\n 210",
    "Location": "Ocean (Lookout, Forest) • Mangrove • Cavern (Water Mine)\nGift (Jim, Spring)",
    "Time": "All Day",
    "Weather": "Sunny",
    "SPR": "✓",
    "SUM": "",
    "FAL": "",
    "WIN": "✓",
    "Rarity": "Rare"
  },
  {
    "Image": "",
    "Name": "Green sawfish",
    "Price": "Base: 845 972\n 1099\n 1268\n 1690",
    "Location": "Estuary\nUnobtainable",
    "Time": "Evening",
    "Weather": "Snow\nBlizzard",
    "SPR": "",
    "SUM": "",
    "FAL": "",
    "WIN": "✓",
    "Rarity": "Legendary"
  },
  {
    "Image": "",
    "Name": "Sturgeon",
    "Price": "Base: 355 408\n 462\n 533\n 710",
    "Location": "River (Farm) • Ocean (Forest) • Cavern (Fire Mine)\nUnobtainable",
    "Time": "Evening\nNight",
    "Weather": "Rain\nWindy\nStorm",
    "SPR": "",
    "SUM": "✓",
    "FAL": "✓",
    "WIN": "✓",
    "Rarity": "Super rare"
  },
  {
    "Image": "",
    "Name": "Sockeye salmon",
    "Price": "Base: 105 121\n 137\n 158\n 210",
    "Location": "Stream • Waterfall • Estuary • Ocean (Lookout) • Lake\nDuring Fall: River (Farm, Forest, Town)\nUnobtainable",
    "Time": "All Day",
    "Weather": "Sunny\nWindy During Fall: Any",
    "SPR": "",
    "SUM": "",
    "FAL": "✓",
    "WIN": "✓",
    "Rarity": "Rare"
  },
  {
    "Image": "",
    "Name": "Shrimp",
    "Price": "Base: 25 29\n 33\n 38\n 50",
    "Location": "Rice Field • Pond • River (Farm, Forest, Town) • Estuary • Ocean (Forest) • Mangrove • Lake",
    "Time": "All Day",
    "Weather": "Any",
    "SPR": "✓",
    "SUM": "✓",
    "FAL": "✓",
    "WIN": "✓",
    "Rarity": "Common"
  },
  {
    "Image": "",
    "Name": "Barramundi",
    "Price": "Base: 105 121\n 137\n 158\n 210",
    "Location": "River (Farm, Forest) • Estuary • Ocean (Beach)Unobtainable",
    "Time": "Morning\nNight",
    "Weather": "Sunny\nRain\nWindy\nStorm",
    "SPR": "",
    "SUM": "",
    "FAL": "✓",
    "WIN": "✓",
    "Rarity": "Rare"
  },
  {
    "Image": "",
    "Name": "Jellyfish",
    "Price": "Base: 230 265\n 299\n 345\n 460",
    "Location": "Ocean (Dock, Lookout) • Cavern (Water Mine)",
    "Time": "Evening\nNight",
    "Weather": "Sunny",
    "SPR": "✓",
    "SUM": "",
    "FAL": "",
    "WIN": "",
    "Rarity": "Super rare"
  },
  {
    "Image": "",
    "Name": "Great white shark",
    "Price": "Base: 845 972\n 1099\n 1268\n 1690",
    "Location": "Ocean (Dock)",
    "Time": "Morning\nAfternoon",
    "Weather": "Sunny\nWindy",
    "SPR": "",
    "SUM": "✓",
    "FAL": "",
    "WIN": "",
    "Rarity": "Legendary"
  },
  {
    "Image": "",
    "Name": "Hammerhead",
    "Price": "Base: 355 408\n 462\n 533\n 710",
    "Location": "Ocean (Lookout)",
    "Time": "Morning\nEvening\nNight",
    "Weather": "Sunny\nSnow\nBlizzard",
    "SPR": "",
    "SUM": "",
    "FAL": "",
    "WIN": "✓",
    "Rarity": "Super rare"
  },
  {
    "Image": "",
    "Name": "Raja Ampat shark",
    "Price": "Base: 310 357\n 403\n 465\n 620",
    "Location": "Ocean (Beach)\nUnobtainable",
    "Time": "Evening\nNight",
    "Weather": "Sunny\nWindy",
    "SPR": "✓",
    "SUM": "",
    "FAL": "",
    "WIN": "",
    "Rarity": "Super rare"
  }
]